<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <div id="info">
        <?php echo @$_SESSION['flash']; ?>
    </div>
    <form action="" method="POST">
        <select name="parent_id">
            <option value="0">root</option>
            <?php echo $parents; ?>
        </select>
        <br>
        <input type="text" name="name" placeholder="Enter name" value="<?php echo @$name; ?>"><br>
        <input type="text" name="description" placeholder="Enter description" value="<?php echo @$description; ?>"><br>
        <input type="hidden" name="id" value="<?php echo @$id; ?>"><br>
        <input type="submit" name="submit" value="save">
    </form>
    <script>
        var items_del = document.getElementsByName("d");
        for(var i = 0; i < items_del.length; i++) {
            items_del[i].addEventListener("click",function(e){
                if(confirm("are you sure?")) {
                    window.location = "index.php?section=admin&del="+(e.target.id).substr(1);
                }
            });
        }
    </script>
    <a href='index.php?section=logout'>logout</a>
</body>
</html>
<?php unset($_SESSION['flash']);